const db = require('./db');
require('dotenv').config();

// Full detail data for all AI tools - sourced from aiTools.ts
const detailData = [
  { name: 'Gemini (Google)', tagline: 'ผู้ช่วยด้านงานเอกสารอัจฉริยะ', difficulty: 'Intermediate', price: 'Free + Paid', whatItDoes: ['ร่างเนื้อหาหนังสือส่งออกทางการ','ร่างข้อตกลงและสัญญา','ปรับใช้ภาษาให้เหมาะสม'], howToUse: [{step:1,text:'ป้อนข้อมูลเบื้องต้นเกี่ยวกับหนังสือส่งออก หรือระบุหัวข้อ ขอบเขตงานในสัญญาให้ AI เขียนให้อัตโนมัติ'}], useCases: ['หนังสือส่งออกหน่วยงานภายนอก','ทำร่างสัญญา MOU เบื้องต้น'], difficultyExplanation: 'ใช้งานง่าย แต่อาจต้องตรวจสอบความถูกต้องทางกฎหมายเพิ่มเติมสำหรับงานสัญญา', pricingDetails: 'มีทั้งเวอร์ชันฟรี และแบบชำระเงินเพื่อความสามารถที่มากขึ้น (Advanced)', plans: [{name:'Gemini (Free)',price:'ฟรี',forOrg:'no',features:'ใช้งานแบบจำกัด'},{name:'Gemini Advanced',price:'~$20',forOrg:'warning',features:'มีความสามารถสูงขึ้น'}], orgSuitability: 'องค์กรสามารถใช้เวอร์ชันฟรีได้ระดับหนึ่ง' },
  { name: 'Claude', tagline: 'วิเคราะห์และร่างโครงสร้างภาษา', difficulty: 'Intermediate', price: 'Free + Paid', whatItDoes: ['เรียบเรียงภาษาให้สละสลวยทางการ','วิเคราะห์และร่างข้อตกลงเชิงตรรกะยาวๆ','จัดโครงสร้างเอกสาร MOU ให้เป็นระเบียบ'], howToUse: [{step:1,text:'ป้อนบริบทและใจความสำคัญให้ Claude หรืออัปโหลดเอกสารตัวอย่างเพื่อจัดรูปแบบสัญญา'}], useCases: ['หนังสือแจ้งนโยบายทางการ','ร่าง TOR โครงการขนาดใหญ่'], difficultyExplanation: 'วิเคราะห์เอกสารยาวได้ดี แต่ควรตรวจสอบข้อความก่อนใช้จริง', pricingDetails: 'มีทั้งเวอร์ชันฟรี และแบบ Pro', plans: [{name:'Free',price:'ฟรี',forOrg:'no',features:'ใช้ Claude รุ่นพื้นฐาน'},{name:'Pro',price:'~$20',forOrg:'warning',features:'รุ่นแรงขึ้น'},{name:'Team',price:'~$25–30',forOrg:true,features:'Workspace รวมทีม'},{name:'Enterprise',price:'ติดต่อเซลส์',forOrg:true,features:'Compliance, API scale'}], orgSuitability: 'องค์กรสามารถใช้ Team หรือ Enterprise' },
  { name: 'ChatGPT', tagline: 'ร่างเนื้อหาในอีเมล', difficulty: 'Beginner', price: 'Free + Paid', whatItDoes: ['สร้างอีเมลจากคีย์เวิร์ด','ปรับระดับภาษาของอีเมล (ทางการ/ไม่ทางการ)'], howToUse: [{step:1,text:'บอกวัตถุประสงค์สั้นๆ แล้วพิมพ์ร้องขอให้เขียนเป็นอีเมล'}], useCases: ['อีเมลแจ้งเตือนลูกค้า','อีเมลสรุปงานให้หัวหน้า'], difficultyExplanation: 'ง่ายมาก พิมพ์เป็นภาษาพูดปกติได้เลย', pricingDetails: 'ใช้งานฟรีด้วยโมเดลมาตรฐาน', plans: [{name:'Free',price:'ฟรี',forOrg:'no',features:'GPT พื้นฐาน, จำกัดการใช้งาน'},{name:'Plus',price:'~$20',forOrg:'warning',features:'GPT รุ่นใหม่กว่า, เร็วขึ้น'},{name:'Team',price:'~$25–30',forOrg:true,features:'แชร์ workspace, admin control'}], orgSuitability: 'ถ้าทำระบบองค์กร → ใช้ Team หรือ Enterprise' },
  { name: 'Microsoft Copilot', tagline: 'ร่างเนื้อหาในอีเมล', difficulty: 'Beginner', price: 'Paid', whatItDoes: ['ร่างอีเมลตอบกลับอัตโนมัติ','สรุปเนื้อหาอีเมลที่ยาวๆ'], howToUse: [{step:1,text:'กดปุ่ม Copilot ในหน้าเขียนอีเมล แล้วระบุสิ่งที่คุณต้องการสื่อสาร'}], useCases: ['ร่างอีเมลภายในองค์กร','ตอบกลับแบบร่างอัตโนมัติ'], difficultyExplanation: 'สะดวกมากเพราะฝังตัวอยู่ในโปรแกรมอีเมล (Outlook) ไม่ต้องสลับแอป', pricingDetails: 'รวมอยู่ในโดเมนหรือต้องซื้อเพิ่มจาก Office/Windows', plans: [{name:'Copilot Pro',price:'~$20',forOrg:'warning',features:'ส่วนบุคคล'},{name:'Microsoft 365 Copilot',price:'~$30',forOrg:true,features:'ใช้ใน Word, Excel, Teams'},{name:'Enterprise',price:'รวมใน Microsoft 365 E3/E5',forOrg:true,features:'Security / Compliance'}], orgSuitability: 'ถ้าองค์กรใช้ Microsoft 365 → Copilot ดีที่สุด' },
  { name: 'Grammarly', tagline: 'ตรวจเช็คความถูกต้อง', difficulty: 'Beginner', price: 'Free + Paid', whatItDoes: ['แก้คำผิด','ตรวจไวยากรณ์ (Grammar)','วัดโทนเสียงของข้อความ'], howToUse: [{step:1,text:'ติดตั้ง Extension แล้วพิมพ์ข้อความ Grammarly จะขีดเส้นใต้คำผิดให้แก้ไข'}], useCases: ['ตรวจรายงาน','เกลาอีเมลภาษาอังกฤษขั้นสุดท้าย'], difficultyExplanation: 'ทำงานแบบ Real-time เวลาพิมพ์ แค่คลิกยอมรับคำแนะนำ', pricingDetails: 'ตรวจตัวสะกดพื้นฐานฟรี ฟีเจอร์ระดับสูงและเกลาประโยคต้องสมัครสมาชิก', plans: [{name:'Free',price:'ฟรี',forOrg:'no',features:'ใช้งานเบื้องต้น'},{name:'Premium',price:'~$12',forOrg:'warning',features:'ใช้งานส่วนบุคคล'},{name:'Business',price:'~$15–25',forOrg:true,features:'สำหรับการใช้งานองค์กร'}], orgSuitability: 'องค์กรใช้ Business ได้' },
  { name: 'DeepL Write', tagline: 'ตรวจเช็คความถูกต้อง', difficulty: 'Beginner', price: 'Free + Paid', whatItDoes: ['เสนอทางเลือกการเขียนรูปประโยคแบบต่างๆ','เกลาประโยคให้อ่านง่ายและเป็นสำนวนที่นิยม'], howToUse: [{step:1,text:'คัดลอกข้อความไปวางในหน้าเว็บ แล้วเลือกคำหรือประโยคที่ AI แนะนำให้เปลี่ยน'}], useCases: ['ปรับปรุงคุณภาพบทความ','ร่างข้อเสนอภาษาต่างประเทศ'], difficultyExplanation: 'ทำงานง่ายด้วยการเลือกแทนที่ข้อความ (Replace)', pricingDetails: 'ใช้ฟรีได้ในจำนวนตัวอักษรที่จำกัด', plans: [{name:'Free',price:'ฟรี จำกัด',forOrg:'no',features:'จำกัดปริมาณคำ'},{name:'Pro',price:'~$8–15',forOrg:'warning',features:'ใช้งานไม่จำกัด'},{name:'Business',price:'มีแพ็กเกจทีม',forOrg:true,features:'แพ็กเกจสำหรับทีม'}], orgSuitability: 'องค์กรใช้ได้ มีแพ็กเกจทีมรองรับ' },
  { name: 'Microsoft Copilot', tagline: 'ร่างเนื้อหาการประชุม (Agenda)', difficulty: 'Beginner', price: 'Paid', whatItDoes: ['วิเคราะห์อีเมลใน Outlook เพื่อเตรียมตารางวาระ','ระบุสิ่งที่ต้องเตรียมตัวใน Calendar'], howToUse: [{step:1,text:'ใช้ Copilot ใน Teams/Outlook ร้องขอให้สรุปเป็น Agenda จากอีเมลล่าสุด'}], useCases: ['ประชุมทีมประจำสัปดาห์','การตั้งปฏิทินส่งวาระนัดหมาย'], difficultyExplanation: 'ต้องทำงานในระบบสภาพแวดล้อมของ Microsoft เป็นหลัก', pricingDetails: 'เป็นส่วนหนึ่งของการสมัครใช้งานขององค์กรแบบมีค่าใช้จ่าย', plans: [{name:'Copilot Pro',price:'~$20',forOrg:'warning',features:'ส่วนบุคคล'},{name:'Microsoft 365 Copilot',price:'~$30',forOrg:true,features:'ใช้ใน Word, Excel, Teams'},{name:'Enterprise',price:'รวมใน Microsoft 365 E3/E5',forOrg:true,features:'Security / Compliance'}], orgSuitability: 'ถ้าองค์กรใช้ Microsoft 365 → Copilot ดีที่สุด' },
  { name: 'Notion AI', tagline: 'ร่างเนื้อหาการประชุม (Agenda)', difficulty: 'Beginner', price: 'Paid', whatItDoes: ['จัดทำ Agenda แบบใส่ Checklist ด้วย AI','สรุปเนื้อหาที่ผ่านมาเพื่อสร้างวาระล่วงหน้า'], howToUse: [{step:1,text:'พิมพ์ /AI เลือกคำสั่งร่างวาระการประชุมในบรรทัดเริ่มต้นของ Notion'}], useCases: ['ประชุม Kick-off โปรเจกต์','ประชุมติดตามงาน 1-on-1'], difficultyExplanation: 'มีเทมเพลตคำสั่งอยู่แล้ว สามารถกดใช้งานได้ทันที', pricingDetails: 'ต้องสมัคร Notion AI แบบเสียเงินเพิ่มเติม', plans: [{name:'Notion AI',price:'ฟรีจำกัด',forOrg:'warning',features:'ใช้งานแบบจำกัด'},{name:'Paid',price:'~$8–10',forOrg:true,features:'ใช้งานได้เต็มรูปแบบ'}], orgSuitability: 'องค์กรใช้ได้ทั้งหมด' },
  { name: 'Fireflies.ai', tagline: 'บันทึกการประชุม (Recording/Minutes)', difficulty: 'Intermediate', price: 'Free + Paid', whatItDoes: ['ถอดเสียงการพูดคุยเป็น Transcribe','ดึงข้อมูล (Action Items) ออกจากไฟล์เสียง'], howToUse: [{step:1,text:'เชิญ Bot ของ Fireflies เข้าร่วมในลิงก์การประชุมเพื่อนั่งจดบันทึก'}], useCases: ['ทำรายงานการประชุม (Minutes)','วิเคราะห์การสัมภาษณ์งาน'], difficultyExplanation: 'ต้องให้สิทธิ์และตกลงให้ Bot เข้าบันทึกเสียง', pricingDetails: 'ทดลองฟรีได้จำกัด หลังจากนั้นอัปเกรดเป็นพรีเมียม', plans: [{name:'Free',price:'ฟรีจำกัด',forOrg:'warning',features:'ถอดบทความจำกัด'},{name:'Paid',price:'~$10–19',forOrg:true,features:'สำหรับการใช้งานองค์กรเต็มรูปแบบ'}], orgSuitability: 'องค์กรใช้ได้ทั้งหมด' },
  { name: 'Otter.ai', tagline: 'บันทึกการประชุม (Recording/Minutes)', difficulty: 'Intermediate', price: 'Free + Paid', whatItDoes: ['แยกผู้พูดแต่ละคนในการถอดความ','ผู้เข้าร่วมสามารถไฮไลต์หรือคอมเมนต์บนข้อความที่ AI ร่างไว้ได้แบบสดๆ'], howToUse: [{step:1,text:'เปิด Otter ให้ฟังเสียงระหว่างการประชุม หรือเชื่อมผ่านแอปพลิเคชันออนไลน์'}], useCases: ['จดคำบรรยายสด','บันทึกสัมภาษณ์พาร์ตเนอร์'], difficultyExplanation: 'เหมาะกับเสียงภาษาอังกฤษ (ภาษาอื่นอาจยังไม่แม่นยำเท่าที่ควร)', pricingDetails: 'มีแผนใช้งานฟรีแบบจำกัดชั่วโมง/เดือน', plans: [{name:'Free',price:'ฟรีจำกัด',forOrg:'warning',features:'ใช้งานจำกัด'},{name:'Paid',price:'~$16+',forOrg:true,features:'สำหรับการใช้งานองค์กรและทีม'}], orgSuitability: 'องค์กรใช้ได้ทั้งหมด' },
  { name: 'Gemini', tagline: 'สรุปประเด็น/รายงาน', difficulty: 'Beginner', price: 'Free + Paid', whatItDoes: ['สรุปข้อความยาวให้กระชับเป็นข้อๆ','สามารถวิเคราะห์ข้อมูลจากไฟล์ Google Docs ได้โดยตรง'], howToUse: [{step:1,text:'โพสต์ Transcript ที่บันทึกมาแล้วสั่งให้ช่วยสรุปประเด็นสำคัญเป็น Action Items'}], useCases: ['สรุปงานประชุมสัมมนา','ตระเตรียมรายงานรายเดือน (Executive Summary)'], difficultyExplanation: 'สามารถโยนไฟล์เข้าไปให้วิเคราะห์ได้สะดวก', pricingDetails: 'สามารถใช้ร่วมกันแบบฟรี', plans: [{name:'Gemini (Free)',price:'ฟรี',forOrg:'no',features:'ใช้งานแบบจำกัด'},{name:'Gemini Advanced',price:'~$20',forOrg:'warning',features:'มีความสามารถสูงขึ้น'}], orgSuitability: 'องค์กรสามารถใช้เวอร์ชันฟรีได้ระดับหนึ่ง' },
  { name: 'ChatGPT', tagline: 'ผู้ช่วยสรุปโน้ตและเขียนข่าว', difficulty: 'Beginner', price: 'Free + Paid', whatItDoes: ['สรุปเป็นประเด็นจากการถอดเสียง','เขียนพาดหัวข่าวและข่าวประชาสัมพันธ์ตามแบบ 5W1H'], howToUse: [{step:1,text:'พิมพ์พรอมต์สรุปข้อความแล้ววางการถอดเสียง หรือสั่งให้ร่างข่าวจากข้อมูลตั้งต้น'}], useCases: ['สรุปคำพูดของผู้บริหาร','ข่าวการเปิดตัวผลิตภัณฑ์ใหม่'], difficultyExplanation: 'แค่พิมพ์ข้อความที่ต้องการ ก็สามารถจัดการงานได้รวดเร็ว', pricingDetails: 'ใช้งานโครงสร้างพื้นฐานได้ฟรี', plans: [{name:'Free',price:'ฟรี',forOrg:'no',features:'GPT พื้นฐาน'},{name:'Plus',price:'~$20',forOrg:'warning',features:'GPT รุ่นใหม่กว่า'},{name:'Team',price:'~$25–30',forOrg:true,features:'แชร์ workspace'}], orgSuitability: 'ถ้าทำระบบองค์กร → ใช้ Team หรือ Enterprise' },
  { name: 'Claude', tagline: 'เขียนข่าว', difficulty: 'Beginner', price: 'Free + Paid', whatItDoes: ['เขียนบทความยาวเพื่อโพสต์เป็นสกู๊ปข่าว','รักษาความถูกต้องของข้อมูลตามที่ป้อน'], howToUse: [{step:1,text:'กำหนดบริบทของเนื้อหาและระบุเป้าหมายสื่อให้ Claude แต่งข่าวเป็นสกู๊ป'}], useCases: ['บทสัมภาษณ์ยาวที่ถูกปรับแต่งเป็นข่าว','ข่าวอ้างอิงเชิงวิเคราะห์'], difficultyExplanation: 'แม่นยำด้านข้อเท็จจริง (ลดการเกิด Hallucination)', pricingDetails: 'ใช้งานฟรีได้แบบจำกัดโควตา', plans: [{name:'Free',price:'ฟรี',forOrg:'no',features:'ใช้ Claude รุ่นพื้นฐาน'},{name:'Pro',price:'~$20',forOrg:'warning',features:'รุ่นแรงขึ้น'},{name:'Team',price:'~$25–30',forOrg:true,features:'Workspace รวมทีม'},{name:'Enterprise',price:'ติดต่อเซลส์',forOrg:true,features:'Compliance, API scale'}], orgSuitability: 'องค์กรสามารถใช้ Team หรือ Enterprise' },
  { name: 'Copy.ai', tagline: 'เขียนข่าว', difficulty: 'Intermediate', price: 'Free + Paid', whatItDoes: ['มีเทมเพลต Press Release สำเร็จรูปให้แก้ไข','ช่วยคิดตัวเลือกพาดหัวหลายชุด'], howToUse: [{step:1,text:'เข้าไปที่เมนู Press Release กรอกข้อมูลรายละเอียดสั้นๆ ลงไป'}], useCases: ['การประกาศเปิดตัวแอปพลิเคชัน','การประกาศชี้แจงข่าวสั้นรายวัน'], difficultyExplanation: 'ง่ายเมื่อใช้ผ่าน Template ที่เตรียมไว้ให้', pricingDetails: 'มีข้อจำกัดสิทธิ์ในตัวแพลตฟอร์มแบบใช้ฟรี' },
  { name: 'Midjourney', tagline: 'สร้างรูปภาพ', difficulty: 'Intermediate', price: 'Paid', whatItDoes: ['สร้างภาพประกอบบทความ','ทำภาพกราฟิกสวยงาม','ภาพแนวคิดล่วงหน้า'], howToUse: [{step:1,text:'ป้อนคีย์เวิร์ดคำอธิบายภาพที่ต้องการลงไปผ่าน Discord'}], useCases: ['ภาพปกโซเชียลมีเดีย','ภาพเนื้อหาประกอบงานออกแบบ'], difficultyExplanation: 'ต้องเรียนรู้วิธีเขียน Prompt เพื่อให้ได้ภาพที่แม่นยำ', pricingDetails: 'ต้องเสียเงินรายเดือน', plans: [{name:'ไม่มีระดับฟรี',price:'❌',forOrg:'no',features:'ต้องสมัครสมาชิก'},{name:'Basic',price:'~$10',forOrg:'warning',features:'ใช้สำหรับบุคคลทั่วไป'},{name:'Standard',price:'~$30',forOrg:'warning',features:'ระดับปานกลาง'},{name:'Pro',price:'~$60',forOrg:true,features:'ใช้ทีมได้'}], orgSuitability: 'ใช้ทีมได้ แต่ไม่มี Enterprise เต็มรูปแบบ' },
  { name: 'Nano Banana (Gemini)', tagline: 'สร้างรูปภาพ', difficulty: 'Beginner', price: 'Free + Paid', whatItDoes: ['สร้างภาพได้รวดเร็ว','รองรับบริบทภาษาได้ดี'], howToUse: [{step:1,text:'พิมพ์รายละเอียดที่ต้องการให้ Gemini วาดบรรยายภาพ'}], useCases: ['ภาพบทความบล็อก','ภาพไอเดียขั้นต้น'], difficultyExplanation: 'ใช้งานง่ายเหมือนพิมพ์คุยกับแชทบอท', pricingDetails: 'สร้างภาพพื้นฐานได้ฟรี' },
  { name: 'Veo (Google)', tagline: 'สร้างคลิปวีดิโอ', difficulty: 'Advanced', price: 'Paid', whatItDoes: ['สร้างวิดีโอความละเอียด 1080p','นำเสนอสไตล์ภาพยนตร์สมจริง'], howToUse: [{step:1,text:'บรรยายฉากที่ต้องการให้ละเอียดเพื่อผลลัพธ์ที่ดีเยี่ยม'}], useCases: ['ทำ B-Roll หรือ Teaser สั้นๆ','ผลิตสต็อกวิดีโอ'], difficultyExplanation: 'เป็นเทคโนโลยีที่ทรงพลังและล้ำสมัย ต้องมีความเข้าใจในการร่างซีนภาพยนตร์', pricingDetails: 'เป็นเครื่องมือในเครือที่ถูกจำกัดการเข้าถึง' },
  { name: 'Sora (OpenAI)', tagline: 'สร้างคลิปวีดิโอ', difficulty: 'Advanced', price: 'Paid', whatItDoes: ['สร้างฉากวิดีโอที่ขยับทิศทางกล้องอย่างสมจริงแบบโลกกายภาพ','เครื่องมือจำลองวิดีโอ'], howToUse: [{step:1,text:'อธิบายรายละเอียดของการเคลื่อนไหวและสถานที่จาก Text To Video'}], useCases: ['ทำจำลองพรีเซนต์เสนองานถ่ายทำ','สร้างแอนิเมชัน'], difficultyExplanation: 'ให้ความลื่นไหลสูง แต่ผู้ใช้ต้องบรรยายให้ละเอียด', pricingDetails: 'สำหรับผู้มีสิทธิการใช้งานระดับพรีเมียม', plans: [{name:'สถานะ',price:'ยังจำกัด',forOrg:'warning',features:'เปิดให้กับผู้เข้าถึงส่วนหนึ่ง'},{name:'ราคา',price:'ยังไม่เปิด public เต็ม',forOrg:'warning',features:'รอการเปิดใช้งานเต็มรูปแบบ'}] },
  { name: 'Runway', tagline: 'สร้างคลิปวีดิโอ', difficulty: 'Intermediate', price: 'Free + Paid', whatItDoes: ['ทำอนิเมชันจากรูปภาพ','ลบวัตถุในวิดีโอ','แต่งวิดีโอจากรูปแบบสไตล์อ้างอิง'], howToUse: [{step:1,text:'อัปโหลดวิดีโอต้นฉบับ หรือภาพนิ่ง และสั่งให้ AI ต่อยอด/ปรับเปลี่ยน'}], useCases: ['เอาภาพนิ่งมาสร้างเคลื่อนไหว','เปลี่ยนฉากหลังวิดีโอ'], difficultyExplanation: 'รูปแบบโปรแกรมเข้าใจง่ายเหมือนเครื่องมือตัดต่อ', pricingDetails: 'ได้รับเครดิตการสร้างฟรี จากนั้นต้องซื้อแพ็กเกจ', plans: [{name:'Free',price:'มีจำกัด',forOrg:'no',features:'ใช้งานแบบมีข้อจำกัด'},{name:'Standard',price:'~$15',forOrg:'warning',features:'ตัดต่อระดับเบื้องต้น'},{name:'Pro',price:'~$35',forOrg:'warning',features:'การทำงานที่มีคุณภาพขึ้น'},{name:'Enterprise',price:'ติดต่อเซลส์',forOrg:true,features:'สำหรับการใช้งานระบบองค์กร'}], orgSuitability: 'องค์กรใช้ได้' },
  { name: 'Gamma', tagline: 'สร้าง Presentation', difficulty: 'Beginner', price: 'Free + Paid', whatItDoes: ['สร้างสไลด์ทั้งชุดและลงภาพประกอบให้','จัดโครงสร้างการอ่านให้อัตโนมัติ'], howToUse: [{step:1,text:'ใส่หัวข้อของพรีเซนต์ หรือวางบทความทั้งหมดเพื่อให้ AI ย่อยข้อมูล'}], useCases: ['สไลด์นำเสนอแผนธุรกิจ','สไลด์รายงานการศึกษาและโปรเจกต์งาน'], difficultyExplanation: 'ระบบทำให้แทบทั้งหมด คุณแค่เข้าไปแต่งสี ปรับคำเพิ่มนิดหน่อย', pricingDetails: 'ฟรีสำหรับการใช้งานเบื้องต้น มีแบบ Pro สำหรับฟีเจอร์พรีเมียม' },
  { name: 'Canva Magic Design', tagline: 'สร้าง Presentation', difficulty: 'Beginner', price: 'Free + Paid', whatItDoes: ['สร้างหน้าพรีเซนต์ที่ตกแต่งพร้อมใช้งาน','เติมเนื้อหาคร่าวๆ และเลือกรูปที่มีใน Canva'], howToUse: [{step:1,text:'กดใช้งาน Magic Design โดยพิมพ์บอกหัวข้อที่ต้องการเป็นประโยค'}], useCases: ['สไลด์ประกอบการขายด่วน','พรีเซนต์นำเสนอชั้นเรียน'], difficultyExplanation: 'คุ้นเคยง่าย แก้ไขต่อสะดวกบนหน้า Canva', pricingDetails: 'เชื่อมต่อรวมในบัญชี Canva โปรแกรมพรีเมียม', plans: [{name:'Free',price:'ฟรี',forOrg:'no',features:'ใช้งานแบบจำกัด'},{name:'Pro',price:'~$12',forOrg:'warning',features:'พรีเมียมส่วนบุคคล'},{name:'Teams',price:'~$15',forOrg:true,features:'สำหรับการใช้งานร่วมกันเป็นทีม'}], orgSuitability: 'องค์กรควรใช้แพลน Teams' },
  { name: 'Suno', tagline: 'สร้างเพลงประกอบ', difficulty: 'Beginner', price: 'Free + Paid', whatItDoes: ['แต่งเพลงใหม่พร้อมเนื้อร้องและดนตรีจากแค่บรรทัดคำสั่งเดียว'], howToUse: [{step:1,text:'บอกแนวเพลง อารมณ์ และเรื่องที่จะร้อง แล้วระบบจะสร้างมาตั้น 2 เพลง'}], useCases: ['เพลงประกอบแคมเปญโซเชียล','เพลงขำขันแจกเพื่อน'], difficultyExplanation: 'ทำได้ง่ายมากๆ ใช้งานผ่านเว็บหรือแอปสื่อได้เลย', pricingDetails: 'มีสิทธิ์การใช้งานรายวันฟรี' },
  { name: 'Udio', tagline: 'สร้างเพลงประกอบ', difficulty: 'Intermediate', price: 'Free + Paid', whatItDoes: ['สร้างเสียง Soundtrack','ปรับแต่งตัวเพลงและต่อเติมท่อนโซโล่ได้ลึกขึ้น'], howToUse: [{step:1,text:'บรรยายรูปแบบเพลงที่คุณต้องการ และใช้งานฟีเจอร์ขยาย (extend)'}], useCases: ['เพลงประกอบ Podcast ที่พรีเมียม','เพลงประกอบวิดีโอโฆษณา'], difficultyExplanation: 'สามารถขยายฟีเจอร์การปรับแต่งได้ซับซ้อนกว่า', pricingDetails: 'ใช้งานสร้างเบื้องต้นได้ฟรี' },
  { name: 'Gemini', tagline: 'ร่างแผนการดำเนินการ', difficulty: 'Beginner', price: 'Free + Paid', whatItDoes: ['แยกงานใหญ่ออกเป็นงานย่อยๆ','หาข้อมูลสนับสนุนและแนวโน้มการตลาด'], howToUse: [{step:1,text:'บอกโจทย์โปรเจกต์ของคุณและให้ Gemini ลิสต์ขั้นตอนมาเป็นลำดับ'}], useCases: ['แผนโปรโมทร้านค้าใหม่','กลยุทธ์การขายรายไตรมาส'], difficultyExplanation: 'ใช้งานง่ายเหมือนการปรึกษาเรื่องแผนกับผู้ช่วย', pricingDetails: 'ใช้งานได้ฟรี', plans: [{name:'Gemini (Free)',price:'ฟรี',forOrg:'no',features:'ใช้งานแบบจำกัด'},{name:'Gemini Advanced',price:'~$20',forOrg:'warning',features:'มีความสามารถสูงขึ้น'}], orgSuitability: 'องค์กรสามารถใช้เวอร์ชันฟรีได้ระดับหนึ่ง' },
  { name: 'ChatGPT', tagline: 'ร่างแผนการดำเนินการ', difficulty: 'Beginner', price: 'Free + Paid', whatItDoes: ['ระบุลำดับความสำคัญของงาน','สร้างระบบตัวชี้วัดความสำเร็จ (KPI) เบื้องต้น'], howToUse: [{step:1,text:'ระบุโจทย์ งบประมาณ เวลา แล้วรับคำแนะนำในการปฏิบัติงาน'}], useCases: ['แผนการต้อนรับพนักงานใหม่ Onboarding','แผนปรับทัพการทำงานองค์กร'], difficultyExplanation: 'ทำความเข้าใจและขอให้ปรับรายละเอียดได้ตลอด', pricingDetails: 'ใช้ฟังก์ชันนี้ในเวอร์ชันฟรีได้ครบถ้วน', plans: [{name:'Free',price:'ฟรี',forOrg:'no',features:'GPT พื้นฐาน'},{name:'Plus',price:'~$20',forOrg:'warning',features:'GPT รุ่นใหม่กว่า'},{name:'Team',price:'~$25–30',forOrg:true,features:'แชร์ workspace'}], orgSuitability: 'ถ้าทำระบบองค์กร → ใช้ Team หรือ Enterprise' },
  { name: 'Notion AI', tagline: 'จัดทำ Timeline เบื้องต้น', difficulty: 'Intermediate', price: 'Paid', whatItDoes: ['สร้างตารางฐานข้อมูลและสรุปวันที่','แจ้งสถานะความคืบหน้าของตาราง'], howToUse: [{step:1,text:'บอกให้ AI ช่วยแปลงแผนงานที่มีให้เป็นฐานข้อมูลพร้อมแถบเวลา'}], useCases: ['งานกำหนดการ Event','กระดาน To-Do List คิวงาน'], difficultyExplanation: 'ต้องรู้จักวิธีการสร้าง Database ของ Notion ระดับหนึ่ง', pricingDetails: 'ฟีเจอร์ AI เป็น Add-on ที่ต้องชำระเพิ่มรายเดือน', plans: [{name:'Notion AI',price:'ฟรีจำกัด',forOrg:'warning',features:'ใช้งานแบบจำกัด'},{name:'Paid',price:'~$8–10',forOrg:true,features:'เพิ่มฟีเจอร์ AI'}], orgSuitability: 'องค์กรใช้ได้ทั้งหมด' },
  { name: 'Asana Intelligence', tagline: 'จัดทำ Timeline เบื้องต้น', difficulty: 'Intermediate', price: 'Paid', whatItDoes: ['สร้าง Task ย่อย','แจ้งคิวงานและเตือนความเสี่ยงของตาราง'], howToUse: [{step:1,text:'ตั้งเป้าหมายใน Asana ให้ AI เสกภารกิจ Timeline เรียงตามลำดับและวันหมดอายุ'}], useCases: ['ติดตามสถานะโปรเจกต์','แผนปล่อยซอฟต์แวร์'], difficultyExplanation: 'คุ้นเคยกับโปรแกรม Asana จะช่วยให้ง่ายขึ้น', pricingDetails: 'เป็นส่วนเสริมระดับที่ต้องชำระค่าใช้งาน', plans: [{name:'Asana Intelligence',price:'~$25+',forOrg:true,features:'รวมอยู่ในแพ็กเกจ Business'}], orgSuitability: 'องค์กรใช้ได้ทั้งหมด' },
  { name: 'NotebookLM (Google)', tagline: 'ผู้ช่วยวิจัยและสรุปเอกสารอัจฉริยะ', difficulty: 'Beginner', price: 'Free', whatItDoes: ['วิเคราะห์และสรุปไฟล์ PDF/Text','สร้าง Podcast (Audio Overview) จากเนื้อหา','ตอบคำถามที่อ้างอิงจากแหล่งข้อมูลที่กำหนดเท่านั้น'], howToUse: [{step:1,text:'อัปโหลดไฟล์เอกสารหรือแหล่งข้อมูลที่ต้องการ แล้วเริ่มถามคำถามหรือให้ AI สรุปประเด็น'}], useCases: ['สรุปบทความวิจัย','เตรียมเนื้อหาสำหรับการเรียนการสอน','เปลี่ยนบันทึกข้อความให้เป็น Podcast'], difficultyExplanation: 'ใช้งานง่ายมาก เพียงแค่อัปโหลดไฟล์และพิมพ์คุยเหมือนแชทบอททั่วไป', pricingDetails: 'ปัจจุบันเปิดให้ใช้งานฟรี' },
  { name: 'Imagen 3 (Google)', tagline: 'โมเดลสร้างภาพคุณภาพสูงจาก Google', difficulty: 'Beginner', price: 'Free', whatItDoes: ['สร้างภาพ Photorealistic ที่สมจริง','รองรับการใส่ข้อความในภาพได้อย่างแม่นยำ','เข้าใจบริบทภาษาที่เป็นธรรมชาติได้อย่างลึกซึ้ง'], howToUse: [{step:1,text:'พิมพ์คำบรรยายภาพที่ต้องการใน Gemini หรือ ImageFX แล้วเลือกสไตล์ที่ต้องการ'}], useCases: ['สร้างภาพประกอบบทความ','ออกแบบแนวคิดงานศิลปะ','สร้างภาพถ่ายจำลอง'], difficultyExplanation: 'เข้าใจคำสั่งภาษาธรรมชาติได้ดี ไม่ต้องใช้เทคนิคการเขียนพรอมต์ที่ซับซ้อนมาก', pricingDetails: 'ใช้งานได้ฟรีผ่านบริการของ Google เช่น Gemini และ ImageFX' },
  { name: 'Project IDX (Google)', tagline: 'เครื่องมือเขียนโค้ดบน Cloud พร้อมพลัง AI', difficulty: 'Intermediate', price: 'Free', whatItDoes: ['ช่วยเขียนโค้ดและแนะนำโค้ดอัจฉริยะ','รองรับการรันแอปพลิเคชันผ่าน Browser','ช่วยแก้ Bug และอธิบายการทำงานของโค้ด'], howToUse: [{step:1,text:'สร้างโปรเจกต์ใหม่บนเว็บ Project IDX และเลือกเทคโนโลยีที่ต้องการใช้งาน'}], useCases: ['เขียนเว็บแอปพลิเคชัน','พัฒนา Mobile App ด้วย Flutter','ทดสอบโค้ดบนสภาพแวดล้อมที่พร้อมใช้งานทันที'], difficultyExplanation: 'เหมาะสำหรับผู้ที่มีพื้นฐานการเขียนโค้ดอยู่แล้ว', pricingDetails: 'ปัจจุบันอยู่ในช่วง Preview และให้ใช้งานได้ฟรี' },
  { name: 'DeepSeek', tagline: 'โมเดลภาษาขั้นสูงเพื่อการวางแผนและจัดการเอกสาร', difficulty: 'Beginner', price: 'Free + Paid', whatItDoes: ['ร่างเนื้อหาเอกสารและบทความ','ช่วยวางแผนกลยุทธ์และลำดับงาน','วิเคราะห์โค้ดและข้อมูลเชิงลึก'], howToUse: [{step:1,text:'พิมพ์คำถามหรือโจทย์ที่ต้องการวางแผน แล้วให้ DeepSeek วิเคราะห์และเสนอแนวทาง'}], useCases: ['ร่างแผนการดำเนินการ','สรุปรายงานการประชุม','ช่วยคิดไอเดียธุรกิจใหม่'], difficultyExplanation: 'ใช้งานง่ายผ่านอินเทอร์เฟซแบบแชทที่เป็นมิตรกับผู้ใช้', pricingDetails: 'มีทั้งเวอร์ชันฟรีและ API สำหรับการใช้งานระดับสูง' },
  { name: 'Perplexity AI', tagline: 'AI ค้นคว้าข้อมูลพร้อมแหล่งอ้างอิงที่เชื่อถือได้', difficulty: 'Beginner', price: 'Free + Paid', whatItDoes: ['ค้นหาข้อมูลแบบตอบคำถามทันที','ระบุแหล่งอ้างอิงและลิงก์ที่เกี่ยวข้อง','สรุปเนื้อหาจากเว็บหลายแหล่งในที่เดียว'], howToUse: [{step:1,text:'พิมพ์หัวเรื่องที่ต้องการศึกษาหรือค้นหาข้อมูลในช่องค้นหา'}], useCases: ['หาข้อมูลวิชาการ','ศึกษาข้อมูลคู่แข่ง','สรุปข่าวสารประจำวัน'], difficultyExplanation: 'เหมือนการใช้ Google แต่ได้รับคำตอบที่สรุปมาให้แล้วพร้อมอ้างอิง', pricingDetails: 'เวอร์ชันฟรีใช้งานได้ดี มี Pro สำหรับโมเดลที่ฉลาดขึ้น' },
  { name: 'Google AI Studio', tagline: 'เครื่องมือพัฒนาและทดสอบโมเดล AI สำหรับสายโค้ด', difficulty: 'Advanced', price: 'Free', whatItDoes: ['ทดสอบและปรับแต่ง Prompt สำหรับโมเดล Gemini','ตั้งค่า Parameter ของโมเดลได้อย่างละเอียด','ส่งออกโค้ดเพื่อนำไปใช้ในแอปพลิเคชัน'], howToUse: [{step:1,text:'ล็อกอินเข้าใช้งานและเลือกโมเดล Gemini ที่ต้องการทดสอบใน Studio'}], useCases: ['ออกแบบระบบ Chatbot','สร้างระบบวิเคราะห์ข้อความอัตโนมัติ','ทดลองความสามารถใหม่ๆ ของ AI'], difficultyExplanation: 'เน้นกลุ่มนักพัฒนาที่เข้าใจการทำงานของโมเดล AI เป็นหลัก', pricingDetails: 'เปิดให้ใช้งานฟรีตามโควตาที่กำหนด' },
  { name: 'Opal', tagline: 'ผู้ช่วยวางแผนและจัดการชีวิตดิจิทัลอย่างปลอดภัย', difficulty: 'Beginner', price: 'Free + Paid', whatItDoes: ['วางแผนตารางเวลาทำงาน (Focus sessions)','บล็อกสิ่งรบกวนสมาธิอัตโนมัติ','วิเคราะห์พฤติกรรมการใช้งานเพื่อเพิ่ม Productivity'], howToUse: [{step:1,text:'ตั้งค่าช่วงเวลาที่ต้องการโฟกัสในแอปเพื่อให้ระบบช่วยจัดการสิ่งรบกวน'}], useCases: ['จัดตารางเวลาทำงานสำคัญ','ลดการใช้งานโซเชียลมีเดียระหว่างงาน','วิเคราะห์สถิติการทำงาน'], difficultyExplanation: 'ตัวแอปออกแบบมาให้ใช้งานง่าย เห็นผลลัพธ์ผ่านกราฟสถิติ', pricingDetails: 'มีเวอร์ชันฟรี และแบบพรีเมียม' },
  { name: 'GitHub Copilot', tagline: 'คู่หู AI สำหรับการเขียนโค้ดที่นักพัฒนาทั่วโลกไว้วางใจ', difficulty: 'Intermediate', price: 'Paid', whatItDoes: ['แนะนำโค้ดอัตโนมัติ (Autocomplete)','ช่วยเขียน Unit Test','อธิบายการทำงานของโค้ดที่ซับซ้อน'], howToUse: [{step:1,text:'ติดตั้ง Extension ใน VS Code หรือ IDE ที่ใช้ แล้วล็อกอินผ่าน GitHub'}], useCases: ['เขียนเว็บแอปพลิเคชัน','พัฒนาอัลกอริทึม','เรียนรู้ภาษาโปรแกรมใหม่ๆ'], difficultyExplanation: 'เหมาะสำหรับคนที่มีพื้นฐานการเขียนโค้ดอยู่แล้ว', pricingDetails: 'มีค่าบริการรายเดือน นักศึกษาและ Open Source ใช้งานฟรี' },
  { name: 'Microsoft Designer', tagline: 'ออกแบบกราฟิกสุดโปรด้วยพลัง AI', difficulty: 'Beginner', price: 'Free', whatItDoes: ['สร้างภาพกราฟิกจากข้อความบรรยาย','ช่วยแนะนำ Layout การจัดวางอัตโนมัติ','ลบพื้นหลังและแก้ไของค์ประกอบภาพได้ง่าย'], howToUse: [{step:1,text:'พิมพ์รายละเอียดที่ต้องการออกแบบ แล้วเลือกสไตล์ที่ระบบแนะนำ'}], useCases: ['ทำภาพหน้าปก Facebook','ออกแบบ Instagram Post','สร้างการ์ดอวยพรออนไลน์'], difficultyExplanation: 'ใช้งานง่ายมากผ่านหน้าเว็บและมือถือ', pricingDetails: 'ปัจจุบันเปิดให้ใช้งานฟรีผ่านบัญชี Microsoft' },
  { name: 'Azure AI Studio', tagline: 'แพลตฟอร์มพัฒนา AI ระดับองค์กรจาก Microsoft', difficulty: 'Advanced', price: 'Free + Paid', whatItDoes: ['จัดการ Life-cycle ของการพัฒนา AI','เข้าถึงและทดสอบโมเดลจากหลายค่าย (OpenAI, Meta)','เน้นการจัดการความปลอดภัยและธรรมาภิบาลข้อมูล'], howToUse: [{step:1,text:'เข้าใช้งานผ่าน Azure Portal และสร้าง Resource สำหรับ AI Studio'}], useCases: ['สร้างระบบ Chatbot ระดับองค์กร','พัฒนา Copilot เฉพาะทาง','จัดการชุดข้อมูลขนาดใหญ่สำหรับ AI'], difficultyExplanation: 'เป็นเครื่องมือระดับ Professional ต้องมีความเข้าใจระบบ Cloud และ AI Development', pricingDetails: 'คิดค่าบริการตามการใช้งาน (Pay-as-you-go) มี Free Trial' },
];

async function migrate() {
  try {
    // Get all tools from DB
    const [rows] = await db.query('SELECT id, name, description FROM ais');
    console.log(`Found ${rows.length} tools in DB`);

    let updated = 0;
    for (const row of rows) {
      // Parse existing JSON
      let existing = {};
      try { existing = JSON.parse(row.description); } catch(e) { existing = {}; }

      // Find matching detail data by name + tagline
      const match = detailData.find(d => 
        d.name === (existing.name || row.name) && d.tagline === (existing.tagline || '')
      );

      if (!match) {
        console.log(`⚠️  No match for ID ${row.id}: "${row.name}" (tagline: "${existing.tagline || 'none'}")`);
        continue;
      }

      // Merge: keep existing data, add missing detail fields
      const merged = { ...existing };
      const fields = ['difficulty','price','whatItDoes','howToUse','useCases','difficultyExplanation','pricingDetails','plans','orgSuitability','bestFor','whoItsFor'];
      for (const f of fields) {
        if (match[f] !== undefined) {
          merged[f] = match[f];
        }
      }

      const newDesc = JSON.stringify(merged);
      await db.query('UPDATE ais SET description = ? WHERE id = ?', [newDesc, row.id]);
      updated++;
      console.log(`✅ Updated ID ${row.id}: ${row.name} (${match.tagline})`);
    }

    console.log(`\nDone! Updated ${updated}/${rows.length} tools.`);
  } catch (err) {
    console.error('Migration failed:', err.message);
  }
  process.exit();
}

migrate();
